name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --clean --onefile --windowed ^
          --icon=orador.ico ^
          --add-binary "%LOCALAPPDATA%\Programs\Python\Python310\python310.dll;." ^
          asignador_reunion.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: asignador_reunion
        path: dist/asignador_reunion.exe
